import time
print("Welcome to the Takbot.")
time.sleep(2)
N=str(input("What is your name? :"))
time.sleep(2)
print("Wow! that is a very good name.")
time.sleep(2)
print("Hello",N,".")
time.sleep(2)
input("How are you? :")
time.sleep(2)
Y=int(input("How old are you? :"))
time.sleep(2)
print("Oh good that you are",Y,"years old.")
time.sleep(2)
print("Did you know that, I was made in the year 2021")
time.sleep(2)
str(input("Do you know who was most popular chess player in 2021. Why dont you quess? : "))
time.sleep(5)
print("It was Magnus Carlsen.")
time.sleep(2)
S=str(input("Which School do you go to? :"))
time.sleep(2)
print("I have heard the name of",S,".","It is a very nice school")
time.sleep(2)
str(input("Do you want to be friends with me? :"))
time.sleep(2)
print("If you like to play games you can play them from the following sites:","\n","1) https://www.gamesgames.com/","\n","2) https://poki.com/","\n","3) https://www.play-games.com/","\n","4) https://www.miniclip.com/games/en/","\n","5) https://www.addictinggames.com/","\n","6) https://www.freeonlinegames.com/")
time.sleep(2)
print("Just copy and then paste the above links in the browser and then just play! play! play!")
time.sleep(5)
input("Bye! and take care:")
time.sleep(2)
input("I hope you enjoyed talking to me.:")
time.sleep(2)
print("Please post your valueable feedback at https://poll-maker.com/poll3979375xAe2F4a71-126 and I promise that your feedback will not be ignored")
time.sleep(120)
quit()


                                
      
 
